services:
  postgres:
    image: postgres:16
    container_name: silicon_cedars_db
    environment:
      POSTGRES_USER: app_owner
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: company_intel
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: